// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesdeElBanquilloApp.Migrations
{
    [DbContext(typeof(AppDesdeElBanquillo))]
    [Migration("20250501043955_Migracion 1")]
    partial class Migracion1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Competition", b =>
                {
                    b.Property<int>("idCompetition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCompetition"));

                    b.Property<DateOnly>("CompetitionEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CompetitionStartDate")
                        .HasColumnType("date");

                    b.Property<int?>("FTeamIdFTeam")
                        .HasColumnType("int");

                    b.Property<int?>("FederationidFederation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("idFederation")
                        .HasColumnType("int");

                    b.HasKey("idCompetition");

                    b.HasIndex("FTeamIdFTeam");

                    b.HasIndex("FederationidFederation");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Country", b =>
                {
                    b.Property<int>("idCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCountry"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("idFederation")
                        .HasColumnType("int");

                    b.HasKey("idCountry");

                    b.HasIndex("idFederation");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.FTeam", b =>
                {
                    b.Property<int>("IdFTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFTeam"));

                    b.Property<int?>("CountryidCountry")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFTeam");

                    b.HasIndex("CountryidCountry");

                    b.ToTable("FTeam");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Federation", b =>
                {
                    b.Property<int>("idFederation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFederation"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("idFederation");

                    b.ToTable("Federation");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Match", b =>
                {
                    b.Property<int>("IdMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatch"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("CompetitionidCompetition")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatchDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMatch");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionidCompetition");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsStarter")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PositionId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("MatchPlayer");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlayer"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("int");

                    b.Property<int>("idCountry")
                        .HasColumnType("int");

                    b.Property<int>("idPosition")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("IdPlayer");

                    b.HasIndex("idCountry");

                    b.HasIndex("idPosition");

                    b.HasIndex("idTeam");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Position", b =>
                {
                    b.Property<int>("IdPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosition"));

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPosition");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Competition", b =>
                {
                    b.HasOne("DesdeElBanquilloApp.Models.FTeam", null)
                        .WithMany("CompetitionFteam")
                        .HasForeignKey("FTeamIdFTeam");

                    b.HasOne("DesdeElBanquilloApp.Models.Federation", "Federation")
                        .WithMany("CompetitionsFederation")
                        .HasForeignKey("FederationidFederation");

                    b.Navigation("Federation");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Country", b =>
                {
                    b.HasOne("DesdeElBanquilloApp.Models.Federation", "Federation")
                        .WithMany("CountriesFederation")
                        .HasForeignKey("idFederation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Federation");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.FTeam", b =>
                {
                    b.HasOne("DesdeElBanquilloApp.Models.Country", null)
                        .WithMany("FTeamsCountry")
                        .HasForeignKey("CountryidCountry");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Match", b =>
                {
                    b.HasOne("DesdeElBanquilloApp.Models.FTeam", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DesdeElBanquilloApp.Models.Competition", null)
                        .WithMany("CompetitionMatches")
                        .HasForeignKey("CompetitionidCompetition");

                    b.HasOne("DesdeElBanquilloApp.Models.FTeam", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.MatchPlayer", b =>
                {
                    b.HasOne("DesdeElBanquilloApp.Models.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesdeElBanquilloApp.Models.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DesdeElBanquilloApp.Models.Position", "Position")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Player", b =>
                {
                    b.HasOne("DesdeElBanquilloApp.Models.Country", "Country")
                        .WithMany("PlayersCountry")
                        .HasForeignKey("idCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesdeElBanquilloApp.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("idPosition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesdeElBanquilloApp.Models.FTeam", "Team")
                        .WithMany("PlayersFteam")
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Competition", b =>
                {
                    b.Navigation("CompetitionMatches");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Country", b =>
                {
                    b.Navigation("FTeamsCountry");

                    b.Navigation("PlayersCountry");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.FTeam", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("CompetitionFteam");

                    b.Navigation("HomeMatches");

                    b.Navigation("PlayersFteam");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Federation", b =>
                {
                    b.Navigation("CompetitionsFederation");

                    b.Navigation("CountriesFederation");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Match", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Player", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("DesdeElBanquilloApp.Models.Position", b =>
                {
                    b.Navigation("MatchPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
